version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: docker/local.Dockerfile
    image: fpland-frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
